export const transformationDomains = [
  {
    id: "workforce-development",
    order: 1,
    title: "Workforce Development",
    promise: "Skills. Careers. Better Futures.",
    pathwayColor: "brilliant-gold",
    icon: "briefcase",
    primaryOutcome: "meaningful-employment",
    relatedDomains: ["education", "economic-mobility", "leadership-development"],
  },
  {
    id: "education",
    order: 2,
    title: "Education",
    promise: "Knowledge Today. Opportunity Tomorrow.",
    pathwayColor: "scholar-gold",
    icon: "graduation-cap",
    primaryOutcome: "knowledge-and-credentials",
    relatedDomains: ["workforce-development", "innovation-and-technology", "entrepreneurship"],
  },
  {
    id: "entrepreneurship",
    order: 3,
    title: "Entrepreneurship",
    promise: "Ideas to Impact. Businesses That Build Communities.",
    pathwayColor: "enterprise-gold",
    icon: "lightbulb",
    primaryOutcome: "business-ownership",
    relatedDomains: ["economic-mobility", "innovation-and-technology", "community-transformation"],
  },
  {
    id: "leadership-development",
    order: 4,
    title: "Leadership Development",
    promise: "Stronger Leaders. Stronger Communities.",
    pathwayColor: "legacy-gold",
    icon: "leadership",
    primaryOutcome: "community-leadership",
    relatedDomains: ["community-engagement", "workforce-development", "community-transformation"],
  },
  {
    id: "economic-mobility",
    order: 5,
    title: "Economic Mobility",
    promise: "Rising Income. Growing Wealth. Changing Lives.",
    pathwayColor: "prosperity-gold",
    icon: "growth-chart",
    primaryOutcome: "financial-advancement",
    relatedDomains: ["workforce-development", "entrepreneurship", "housing-stability"],
  },
  {
    id: "housing-stability",
    order: 6,
    title: "Housing Stability",
    promise: "Stable Homes. Stronger Families. Stronger Communities.",
    pathwayColor: "shelter-gold",
    icon: "home",
    primaryOutcome: "stable-housing",
    relatedDomains: ["resource-navigation", "economic-mobility", "community-transformation"],
  },
  {
    id: "resource-navigation",
    order: 7,
    title: "Resource Navigation",
    promise: "The Right Help. At the Right Time. No One Walks Alone.",
    pathwayColor: "guidance-gold",
    icon: "compass",
    primaryOutcome: "coordinated-access",
    relatedDomains: ["housing-stability", "workforce-development", "community-engagement"],
  },
  {
    id: "community-engagement",
    order: 8,
    title: "Community Engagement",
    promise: "Connection. Belonging. Shared Purpose.",
    pathwayColor: "community-gold",
    icon: "people",
    primaryOutcome: "civic-belonging",
    relatedDomains: ["leadership-development", "resource-navigation", "community-transformation"],
  },
  {
    id: "innovation-and-technology",
    order: 9,
    title: "Innovation & Technology",
    promise: "Future Ready. Solutions That Transform.",
    pathwayColor: "digital-gold",
    icon: "network",
    primaryOutcome: "digital-capacity",
    relatedDomains: ["education", "entrepreneurship", "workforce-development"],
  },
  {
    id: "community-transformation",
    order: 10,
    title: "Community Transformation",
    promise: "Revitalize. Rebuild. Leave a Legacy.",
    pathwayColor: "transformation-gold",
    icon: "city",
    primaryOutcome: "lasting-community-impact",
    relatedDomains: ["community-engagement", "leadership-development", "economic-mobility"],
  },
] as const;
